### ISSUE TITLE
May I inquire about Formpost & ACLS from you?

### ISSUE THREAD

**Issue by dsljjmark** [cschwede/django-swiftbrowser#11]
May I inquire about Formpost & ACLS from you?
 
 
As I know, Formpost requires a key (X-Account-Meta-Temp-URL-Key) to run and it works together with ACLS. 
 
When I started working on ACLS and tried to assign a user to each Container, I could not get any key. 
It always denied me and popped up Access Denied message. 
 
Would you pls guide me how to get the key on ACLS, in order to use it on Formpost?
Or how both can work together?

**Comment by cschwede** [comment]
The X-Account-Meta-Temp-URL-Key required for formpost (and tempurl) is not tied to ACLs. You need account ownership to read (and set) that key; and if you have the key you can write and read from all containers, no matter what kind of ACL is set. This is he reason why you can't get the key: you need to be an account owner.
Keys for a specific container were added recently: https://github.com/openstack/swift/commit/489dd5ff
They work in a similar way to the X-Account-Meta-Temp-URL-Key, meaning that they allow read and write access to that container, regardless of any ACLs set.
Please join #openstack-swift on IRC (freenode) if you have more questions regarding ACLs and formpost.

**Comment by Huups** [comment]
Could you suggest me for question
I have 3 account
1. Username : "Admin" (Role Admin is tenant owner)
2. Username : "A" (Role Member)
3. Username : "B" (Role Member)

1. Admin create 2 container "ContainerA" and "ContanierB" i hope A only access on "ContainerA" and B only access on "ContainerB"
2. "Admin" add ACLS Read/Write "A","B" to "ContainerA", "ContainerB"
3. That's work when i testing with curl,Restful API, user can Create,Upload,Delete object
4. But i tried to use #django-swiftbrowser login by "A" customize "Login" method for bypass ListContainer to ListContainer "ContainerA" list file folder is work, but i can't upload or download file 

Thank you
Joh

**Comment by cschwede** [comment]
Hello Joh,

unfortunately this is currently not possible. formpost and tempurl (the middlewares used in django-swiftbrowser) require an account temp url key, and to read and set the key one needs to be an account administrator.

I'm currently looking into using direct PUT/GET requests, for example using AngularJS. This requires some changes, I'm working on it.

**Comment by dsljjmark** [comment]
thank you :)

**Comment by Huups** [comment]
Thank you cschwede.
