### ISSUE TITLE
It returns 400 after setting up swift

### ISSUE THREAD

**Issue by tobegit3hub** [cschwede/django-swiftbrowser#16]
I have run swift in container and it works with `swift` command-line client.

After setting up django-swiftbrowser, it returns Bad Request(400) when I access on browser. Should I edit `swiftbrowser.settings` or do any extra configuration?

**Comment by manoj-ms** [comment]
When do you get this error? Do you see login page at least ? Please share the screen shot and share settings files from django browser. Ensure auth url are and storage auth are updated in settings file

**Comment by tobegit3hub** [comment]
Thanks for replying @manoj-ms 

I could not see the login page and that returns 400 in browser. Where can I find the django setting files and its log?

**Comment by manoj-ms** [comment]
/use/local/lib/Python{version}/dist-packages/swiftbrowser

**Comment by cschwede** [comment]
Thanks for the bugreport and the comments!

I just cut a bugfix release, please upgrade to 0.21 to make use of it.

pip install -U django-swiftbrowser

That fixes the 400 (500) errors on recent Django versions.

Please let me know if this works for you.

**Comment by tobegit3hub** [comment]
Well, it works like a charm after upgrading. Thanks @cschwede :+1:
