### ISSUE TITLE
not able to share container to another user

### ISSUE THREAD

**Issue by manoj-ms** [cschwede/django-swiftbrowser#17]
have two users:
 User A
 User B.

I have created container-A and uploaded file-A as user A. modified Container's ACL and granted read rights to user B. Yet, user B is not able to see container-A

**Comment by cschwede** [comment]
If you grant another user access to a container it will not be listed automatically in the other users account. This is a default behavior within Swift, and thus django-swiftbrowser can't list this container.

**Comment by manoj-ms** [comment]
Thanks for reply.

Perhaps I'm missing the format:

It says account:username. Hence I am using auth_user1:user1

Picked up account name from output of swift stat -v

There is no error on the django browser. It says acl updated successfully. However, I do not the reader and writer keys updated on container header.

On 19-Jan-2016, at 1:53 PM, Christian Schwede <notifications@github.com<mailto:notifications@github.com>> wrote:


If you grant another user access to a container it will not be listed automatically in the other users account. This is a default behavior within Swift, and thus django-swiftbrowser can't list this container.

-

**Comment by cschwede** [comment]
Do you see the added ACLs in swiftbrowser itself? For example, this is a screenshot after adding a few sample ACLs on a swift-all-in-one VM:
<img width="1280" alt="swiftbrowser" src="https://cloud.githubusercontent.com/assets/3287593/12796462/218a476e-cabf-11e5-9a5f-07073434024c.png">

Does setting ACLs work using the CLI? For example like this:

swift post -w "some:user" -r "another:one" containername

**Comment by manoj-ms** [comment]
No more an issue. Closing.
