### ISSUE TITLE
500 on Upload and Download

### ISSUE THREAD

**Issue by jahantech** [cschwede/django-swiftbrowser#18]
Hi, 
I have configured swift browser on my proxy server. I can authenticate users and can create/delete containers. However when I try to upload or download a file I get 500. 

Strangely I am also able to delete a file in container. 

formpost and tempurl middleware are enabled. 

Would you be able to assist, what is causing this?

I don't see any error related to this in the proxy.error file. Also SE Linux is set to permissive.
Thanks, 
Jahan

I ran swift browser with debug switched on and was able to get the traceback: 

```
Environment:

Request Method: GET
Request URL: http://xx.xx.xx.xx:8000/upload/JAHANSCONTAINER/

Django Version: 1.9.1
Python Version: 2.7.5
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.staticfiles',
 'swiftbrowser')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.http.ConditionalGetMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware')



Traceback:

File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/lib/python2.7/site-packages/django_swiftbrowser-0.21-py2.7.egg/swiftbrowser/views.py" in upload
  190.     signature = hmac.new(key, hmac_body, sha1).hexdigest()

File "/usr/lib64/python2.7/hmac.py" in new
  136.     return HMAC(key, msg, digestmod)

File "/usr/lib64/python2.7/hmac.py" in __init__
  75.         self.outer.update(key.translate(trans_5C))

Exception Type: TypeError at /upload/JAHANSCONTAINER/
Exception Value: character mapping must return integer, None or unicode
```

**Comment by jahantech** [comment]
I have managed to pass 500 error by casting key and msg variables before sending them to HMAC function. 
Now when I try to download the file or upload to the file. Server redirects to me localhost, but as I am using this from a remote host, it is not good for me. Maybe there is a setting somewhere to set the IP address ?
```
Temporary URL for JAHANSCONTAINER/manage.py
Use the following URL to share this object. The URL is valid for 7 days.

http://127.0.0.1:8080/v1/AUTH_c3d9a38d-d5fc-4252-8426-a5bcb4f71182/JAHANSCONTAINER/manage.py?temp_url_sig=a29db7b5950e96952d2d6ae29fe318b7e419ffc6&temp_url_expires=1454675809

Please note that you cannot revoke this URL. It is valid until expiration!
```

**Comment by jahantech** [comment]
I have got it working. For some reason the code didn't pick values from the settings file. So I just added a string replace around the url code to get it working for my server.

**Comment by cschwede** [comment]
Thanks for this bugreport!

I fixed this upstream and pushed a new release to pypi.

The reason why the change is not picked up from a changed configuration file might be the session cookie - it should be regenerated once you logged out. The url set in SWIFT_AUTH_URL should be used when generating the final tempurl.
