### ISSUE TITLE
Cant upload file through django browser in container

### ISSUE THREAD

**Issue by abdlh** [cschwede/django-swiftbrowser#6]
Im trying to upload a file from the host which is my laptop through django, an authorization issue pop up on the web stated that the server could not verify whether i  am authorized to access the document on my laptop. however im able to upload the file by swift CLI. Which part do i need to do some changes?

**Comment by cschwede** [comment]
Can you share more details? What is the exact message that you get? Are you running Djangos built-in testserver?

**Comment by abdlh** [comment]
The prompt message stated is as shown below:
"Unauthorized" 
"this server could not verify that you are authorized to access the document you requested"


Yes, im running the default Django Swiftbrowser built in testserver on my laptop. Im using the test account and loopback device for my swift storage.

**Comment by cschwede** [comment]
Is the formpost middleware enabled in the Swift proxy? And the user is the account owner?

**Comment by abdlh** [comment]
Yup i followed all the steps on the installation and config part. But how do i determine the account owner? Im not pretty sure about how to check on that.

**Comment by cschwede** [comment]
If you're using a SAIO (Swift all in one - http://docs.openstack.org/developer/swift/development_saio.html) it is test:tester. The account owner is a user that is able to create new containers for example, or set/get account metadata (which is the important task in this case).

Are there no errors reported on the console (from the testserver)?

**Comment by abdlh** [comment]
Thanks for the brief explanation, and yes i am using SAIO with the account and user test:tester. 
 
This is what appeared in the console, no errors.

[08/Jan/2015 18:37:50] "GET / HTTP/1.1" 200 6050
[08/Jan/2015 18:37:56] "GET /objects/TUPPERWARE/ HTTP/1.1" 200 6471
[08/Jan/2015 18:38:49] "GET /upload/TUPPERWARE/ HTTP/1.1" 200 3954

**Comment by abdlh** [comment]
My proxy-server.conf

[DEFAULT]
bind_ip = 127.0.0.1
bind_port = 8080
workers = 1
user = snowl
log_facility = LOG_LOCAL1
eventlet_debug = false

[pipeline:main]
# Yes, proxy-logging appears twice. This is so that
# middleware-originated requests get logged too.
pipeline = catch_errors gatekeeper healthcheck proxy-logging cache bulk tempurl slo dlo ratelimit crossdomain tempauth staticweb container-quotas account-quotas proxy-logging proxy-server

[filter:list-endpoints]
use = egg:swift#list_endpoints

[filter:catch_errors]
use = egg:swift#catch_errors

[filter:healthcheck]
use = egg:swift#healthcheck

[filter:proxy-logging]
use = egg:swift#proxy_logging

[filter:bulk]
use = egg:swift#bulk

[filter:ratelimit]
use = egg:swift#ratelimit

[filter:crossdomain]
use = egg:swift#crossdomain

[filter:dlo]
use = egg:swift#dlo

[filter:slo]
use = egg:swift#slo

[filter:tempurl]
use = egg:swift#tempurl

[filter:formpost]
use = egg:swift#formpost

[filter:tempauth]
use = egg:swift#tempauth
user_admin_admin = admin .admin .reseller_admin
user_test_tester = testing .admin
user_test2_tester2 = testing2 .admin
user_test_tester3 = testing3
user_qwerty_qwerty = qwerty .admin
user_user123_user123 = user123
user_dol_dol = dol .admin

[filter:staticweb]
use = egg:swift#staticweb

[filter:account-quotas]
use = egg:swift#account_quotas

[filter:container-quotas]
use = egg:swift#container_quotas

[filter:cache]
use = egg:swift#memcache

[filter:gatekeeper]
use = egg:swift#gatekeeper

[app:proxy-server]
use = egg:swift#proxy
allow_account_management = true
account_autocreate = true

**Comment by cschwede** [comment]
You are missing the formpost middleware in your pipeline, please add it and restart your proxy server:

pipeline = catch_errors gatekeeper healthcheck proxy-logging cache bulk tempurl formpost slo dlo ratelimit crossdomain tempauth staticweb container-quotas account-quotas proxy-logging proxy-server

**Comment by abdlh** [comment]
I added the formpost but then i can not seem to run the service swift-proxy restart command.

snowl@snowL:~$ service swift-proxy restart
swift-proxy: unrecognized service

Still can not upload file.

**Comment by cschwede** [comment]
How did you start the proxy earlier? Which distribution are you using? Did you install Swift from source or using a package?

If the proxy is running you can get some info about active middlewares using the following command (if you're using a recent version of Swift):

 curl http://127.0.0.1:8080/info | python -mjson.tool

The formpost middleware is required, otherwise it is not possible to upload. The formpost middleware handles the authentication for uploads, and the tempurl middleware for downloads.

**Comment by abdlh** [comment]
I just start the proxy with startmain.  Im using ubuntu 12.04 LTS 64bit. I installed swift from source stated exactly in the SAIO guideline. 

This is the info stated. 

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1118  100  1118    0     0   257k      0 --:--:-- --:--:-- --:--:--  272k
{
    "account_quotas": {}, 
    "bulk_delete": {
        "max_deletes_per_request": 10000, 
        "max_failed_deletes": 1000
    }, 
    "bulk_upload": {
        "max_containers_per_extraction": 10000, 
        "max_failed_extractions": 1000
    }, 
    "container_quotas": {}, 
    "crossdomain": {}, 
    "ratelimit": {
        "account_ratelimit": 0.0, 
        "container_listing_ratelimits": [], 
        "container_ratelimits": [], 
        "max_sleep_time_seconds": 60.0
    }, 
    "slo": {
        "max_manifest_segments": 1000, 
        "max_manifest_size": 2097152, 
        "min_segment_size": 1048576
    }, 
    "staticweb": {}, 
    "swift": {
        "account_autocreate": true, 
        "account_listing_limit": 10000, 
        "allow_account_management": true, 
        "container_listing_limit": 10000, 
        "max_account_name_length": 256, 
        "max_container_name_length": 256, 
        "max_file_size": 5368709122, 
        "max_header_size": 8192, 
        "max_meta_count": 90, 
        "max_meta_name_length": 128, 
        "max_meta_overall_size": 4096, 
        "max_meta_value_length": 256, 
        "max_object_name_length": 1024, 
        "policies": [
            {
                "default": true, 
                "name": "gold"
            }, 
            {
                "name": "silver"
            }
        ], 
        "strict_cors_mode": true, 
        "version": "2.2.0.45.g2792fe8"
    }, 
    "tempauth": {
        "account_acls": true
    }, 
    "tempurl": {
        "methods": [
            "GET", 
            "HEAD", 
            "PUT", 
            "POST", 
            "DELETE"
        ]
    }
}

**Comment by abdlh** [comment]
Additional details fyi, i am able to execute other functions in Swiftbrowser as in view and download the files that i have uploaded in swift by command line. The only function that can not be executed in Swiftbrowser is uploading a file/doc in the container. (all actions under test:tester)

**Comment by cschwede** [comment]
Yes, and the reason is the missing formpost middleware in the proxy pipeline.

Could you please add it and do a "swift-init restart proxy"?

**Comment by abdlh** [comment]
That command line works like a charm, thanks alot. Anyhow right after uploading, the webpage does not return to the container list page where else it pop up a blank white webpage stating Bad URL. I need to manually go back one page to entire the container list page.

**Comment by abdlh** [comment]
i want to edit the page after the upload page so that it can be redirect back to the container view list but i cant seem to find the html file in the www folder directory in ubuntu.

**Comment by cschwede** [comment]
There is a small bug in the example/settings.py file, the port is missing and thus the redirect doesn't work.

Please use the following setting in myproj/settings.py:

 BASE_URL = 'http://127.0.0.1:8000'

I also updated the included example/settings.py.

Please let me know if this works for you.

**Comment by abdlh** [comment]
Thanks a lot it works. The sum of Objects and Size in the Container view list are not updated when i upload or delete objects. And if i have account1 that is on account2 's ACL, how does account1  access the shared file since there is no notification on saying it is on account2 's ACL ?

**Comment by cschwede** [comment]
Great that it works now for you!

About the stats: this is due to the eventual consistency. Stats are updated by several Swift services, for example container-updater.

Cross-account sharing like you describe is provided by Swift, but you won't see these shared containers in your account listing. You need to know the storage URL of the other account. This might be added to django-swiftbrowser in the later future.

I'm closing this github issue; feel free to ping me directly or meet me on IRC ( #openstack-swift on freenode).
